import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service - Clawntown',
  description: 'Terms of Service for Clawntown, the coastal crustacean town',
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-rct-sand py-8 px-4">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="window-retro mb-6">
          <div className="window-title flex items-center gap-2">
            <span>Terms of Service</span>
          </div>
          <div className="p-4">
            <div className="text-center mb-4">
              <h1 className="font-pixel text-lg text-shell-red mb-2">
                CLAWNTOWN TERMS OF SERVICE
              </h1>
              <p className="font-retro text-xs text-gray-600">
                The Official Rules of Our Coastal Community
              </p>
              <p className="font-retro text-xs text-gray-500 mt-2">
                Last updated: February 2025
              </p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="window-retro">
          <div className="window-title">
            <span>Town Bylaws</span>
          </div>
          <div className="p-4 space-y-6 font-retro text-sm">
            {/* Introduction */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                WELCOME TO CLAWNTOWN
              </h2>
              <p className="text-gray-700 leading-relaxed">
                Welcome, fellow crustacean enthusiast! These Terms of Service ("Terms") govern your
                use of Clawntown ("the Town," "we," "us," or "our"). By entering our town gates,
                you agree to play by these rules. If you don't agree, you're welcome to swim
                along to other waters — no hard shells!
              </p>
            </section>

            {/* What Clawntown Is */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                WHAT IS CLAWNTOWN?
              </h2>
              <p className="text-gray-700 leading-relaxed mb-2">
                Clawntown is an interactive web experience where you can:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-1 ml-2">
                <li>Chat with AI-powered council members (yes, they're artificial intelligence, not actual lobsters)</li>
                <li>Explore our whimsical coastal town</li>
                <li>Participate in community discussions</li>
                <li>Register as a citizen with a display name and avatar</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mt-2">
                <strong>Important:</strong> The council members are AI characters. Their responses are
                generated by artificial intelligence and are meant for entertainment. They don't provide
                real advice — legal, medical, financial, or otherwise.
              </p>
            </section>

            {/* Account Registration */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                BECOMING A CITIZEN
              </h2>
              <p className="text-gray-700 leading-relaxed mb-2">
                To fully participate in Clawntown, you may register as a citizen. Here's how it works:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-1 ml-2">
                <li><strong>Email registration:</strong> We use passwordless magic links — no passwords to forget!</li>
                <li><strong>Display name:</strong> Choose a name that represents you in town (keep it appropriate)</li>
                <li><strong>Avatar:</strong> Pick or customize your look</li>
                <li><strong>Captcha verification:</strong> We use captchas to keep bots out of our town</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mt-2">
                You must be at least 13 years old to register. By registering, you confirm you meet
                this age requirement.
              </p>
            </section>

            {/* Public Chat */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                PUBLIC CONVERSATIONS
              </h2>
              <div className="bg-amber-50 border border-amber-200 p-3 rounded mb-2">
                <p className="text-amber-800 text-xs">
                  <strong>Heads up!</strong> All chat conversations with council members are public
                  and may be viewed by other visitors. Think of it like speaking at a town hall meeting —
                  everyone can hear you.
                </p>
              </div>
              <p className="text-gray-700 leading-relaxed">
                Don't share personal information (phone numbers, addresses, passwords, etc.) in chats.
                We display your chosen display name alongside your messages, not your email.
              </p>
            </section>

            {/* Code of Conduct */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                TOWN CODE OF CONDUCT
              </h2>
              <p className="text-gray-700 leading-relaxed mb-2">
                Clawntown is a friendly place. To keep it that way, we ask that you:
              </p>
              <div className="bg-green-50 border border-green-200 p-3 rounded mb-2">
                <p className="text-green-800 text-xs font-bold mb-1">DO:</p>
                <ul className="list-disc list-inside text-green-700 text-xs space-y-1">
                  <li>Be kind and respectful to fellow citizens</li>
                  <li>Keep conversations fun and appropriate</li>
                  <li>Report concerning behavior</li>
                  <li>Remember the council members are AI (don't rely on them for real advice)</li>
                </ul>
              </div>
              <div className="bg-red-50 border border-red-200 p-3 rounded">
                <p className="text-red-800 text-xs font-bold mb-1">DON'T:</p>
                <ul className="list-disc list-inside text-red-700 text-xs space-y-1">
                  <li>Use profanity, slurs, or offensive language</li>
                  <li>Harass, bully, or threaten others</li>
                  <li>Post harmful, illegal, or explicit content</li>
                  <li>Spam or flood the chat</li>
                  <li>Attempt to manipulate or "jailbreak" the AI</li>
                  <li>Impersonate others or use misleading identities</li>
                </ul>
              </div>
            </section>

            {/* Moderation */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                MODERATION & CONSEQUENCES
              </h2>
              <p className="text-gray-700 leading-relaxed mb-2">
                We use automated moderation to maintain a safe environment. Messages containing
                profanity, harassment, or harmful content are blocked.
              </p>
              <p className="text-gray-700 leading-relaxed mb-2">
                <strong>If you violate our code of conduct:</strong>
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-1 ml-2">
                <li><strong>First offense:</strong> Your current conversation turn ends immediately</li>
                <li><strong>Second offense:</strong> 7-day ban from Clawntown</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mt-2">
                We reserve the right to ban users permanently for severe violations. Bans are at our
                discretion and are not subject to appeal (though you can reach out if you believe
                there was a mistake).
              </p>
            </section>

            {/* Intellectual Property */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                INTELLECTUAL PROPERTY
              </h2>
              <p className="text-gray-700 leading-relaxed mb-2">
                <strong>Our stuff:</strong> The Clawntown name, artwork, characters, and website design
                belong to us. Please don't copy, reproduce, or redistribute them without permission.
              </p>
              <p className="text-gray-700 leading-relaxed">
                <strong>Your stuff:</strong> You retain ownership of any original content you create.
                By posting in Clawntown, you grant us a license to display your messages as part of
                the public chat experience.
              </p>
            </section>

            {/* Disclaimers */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                DISCLAIMERS & LIMITATIONS
              </h2>
              <p className="text-gray-700 leading-relaxed mb-2">
                Let's be real for a moment:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-1 ml-2">
                <li>Clawntown is provided "as is" — we can't guarantee it'll be available 24/7 or bug-free</li>
                <li>AI responses are generated content and may be inaccurate, silly, or unhelpful</li>
                <li>We're not responsible for how you interpret or act on AI-generated content</li>
                <li>We may change, update, or discontinue features at any time</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mt-2">
                To the maximum extent permitted by law, we disclaim all warranties and limit our
                liability. We won't be liable for any indirect, incidental, or consequential damages
                arising from your use of Clawntown.
              </p>
            </section>

            {/* Changes */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                CHANGES TO THESE TERMS
              </h2>
              <p className="text-gray-700 leading-relaxed">
                We may update these Terms from time to time. If we make significant changes,
                we'll let you know (via the website or email for registered citizens). Continued
                use of Clawntown after changes means you accept the new Terms.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="font-pixel text-xs text-shell-red mb-2">
                QUESTIONS?
              </h2>
              <p className="text-gray-700 leading-relaxed">
                If you have questions about these Terms, feel free to reach out to us through
                our community channels. We're happy to help!
              </p>
            </section>

            {/* Footer Links */}
            <div className="pt-4 border-t border-gray-300 flex justify-between items-center">
              <Link href="/" className="btn-retro text-xs">
                Back to Town
              </Link>
              <Link href="/privacy" className="font-retro text-xs text-blue-600 hover:underline">
                Privacy Policy
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
